.Dd $Mdocdate$
.Dt DMTR 1 URM
.Os
.Sh NAME
.Nm dmtr
.Nd a system ping wrapper for network diagnostic
.Sh SYNOPSIS
.Nm
.Op Fl achijnpqrstw46
TARGET ...
.Sh DESCRIPTION
A network diagnostic tool based on parsing system
.Sy ping
output with functionality of
.Sy traceroute
and ncurses look of
.Sy mtr .
.br
It doesn't require a set-root-uid or raw-socket-perms to run
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a, Fl -address Ar IP-ADDRESS | INTERFACE-NAME
Source
.Ar address
or
.Ar interface
name
.It Fl c, Fl -cycles Ar NUMBER
Run
.Ar number
of cycles per target
.It Fl f, Fl -fields Ar KEYS
Statistics fields which match "[lsmbw aj]+" pattern
.br
Keys stand for: Loss Sent Last(msec) Best Worst <space> Average Jitter
.It Fl i, Fl -interval Ar SECONDS
Interval in
.Ar seconds
between pings
.br
Default 1
.It Fl p, Fl -payload Ar PATTERN
Payload
.Ar pattern
in hex notation, upto 16 bytes (32 hex characters)
.It Fl q, Fl -qos Ar BITS
QoS/ToS
.Ar byte
(0..255) in outgoing pings
.It Fl s, Fl -size Ar BYTES
Payload
.Ar size ,
minimum is 16 (timestamp size), maximum is 9000-20-8
.br
Default 56
.It Fl t, Fl -ttl Ar MIN,MAX
TTL
.Ar range
to ping, it can be partially set as
.Ar MIN
or as
.Ar ,MAX
too
.br
Default 1,30
.It Fl w, Fl -whois Ar KEYS
RIS whois keys which match "[acdr]+|" pattern (AS Country Description Route)
.br
Default "ca" (Country AS) is aliased to
.Fl w-
.It Fl n, Fl -numeric
Numeric output (i.e. disable DNS resolve)
.br
Note: if you set a
.Ar target
as IP-address, pings will run in numeric mode too
.It Fl r, Fl -report
Print simple report at exit
.br
Default number of cycles is 10 in report mode
.It Fl j, Fl -json
Print report in JSON format at exit
.br
Default number of cycles is 10 in JSON output mode
.It Fl 4, Fl -ipv4
IPv4 only
.It Fl 6, Fl -ipv6
IPv6 only
.It Fl h, Fl -help
Show help and exit
.It Fl -syslog
Send debug messages to syslog
.El
.Sh KNOWN CAVEATS
RTT for transit hops is calculated from TIMESTAMPS generated by
.Sy ping
for
.Sy no-answer-yet
and
.Sy time-to-live-exceeded
messages, so that use
.Sy traceroute
or
.Sy mtr
for more accurate stats of transit hops
.El
.Sh PROJECT LOCATION
.Lk https://github.com/yvs2014/dmtr
.El
.Sh SEE ALSO
ping(8), traceroute(8), mtr(8)
