
name: dmtr
description: Pinger with a look like 'mtr' written in Dart
version: 0.1.0
repository: https://github.com/yvs2014/dmtr

environment:
  sdk: ^3.0.2

# Add regular dependencies here
dependencies:
  ffi: ^2.0.2
  args: ^2.4.2
  sprintf: ^7.0.0
  dping4mtr: ^0.1.0

dependency_overrides:
  dping4mtr:
    git:
      url: https://github.com/yvs2014/dping4mtr

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

