
name: dmtr
description: Pinger with a look like 'mtr' written in Dart
version: 1.0.0
repository: https://github.com/yvs2014/dmtr

environment:
  sdk: ^3.0.2

# Add regular dependencies here
dependencies:
  args: ^2.4.2
  dping4mtr: ^0.0.1
  ncurses: ^0.1.0
  sprintf: ^7.0.0

dependency_overrides:
  dping4mtr:
    git:
      url: https://github.com/yvs2014/dping4mtr

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

