
name: dmtr
description: sys ping wrapper in dart with a look like 'mtr'
version: 0.1.37
repository: https://github.com/yvs2014/dmtr

environment:
  sdk: ^3.0.0

# Add regular dependencies here
dependencies:
  ffi: ^2.0.0
  args: ^2.0.0
  async: ^2.11.0
  sprintf: ^7.0.0
  collection: ^1.17.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.0.0

