name: dmtr
adopt-info: dmtr
base: core22
version: '0.1.51'
summary: a system ping wrapper for network diagnostic
description: |
  A network diagnostic tool based on parsing system 'ping' output
  with functionality of 'traceroute' and ncurses look of 'mtr'

architectures:
  - build-on: amd64
  - build-on: arm64
grade: stable
confinement: strict

apps:
  dmtr:
    command: usr/bin/dmtr
    plugs:
      - network
      - network-control
#      - system-observe # for dart itself?

parts:
  dmtr:
    plugin: make
    source-type: git
    source: https://github.com/yvs2014/dmtr.git
    build-packages:
      - build-essential
      - libncurses-dev
    build-environment:
      - PREFIX: /usr
    override-build: |
      apt install -y snapd
      snap install flutter --classic
      flutter --version
      craftctl default
    stage-packages:
      - iputils-ping
      - libncurses6
    prime:
      - usr/bin/dmtr
      - usr/share/man/man1/dmtr.1.gz

