name: build_and_run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_on_linux_and_run:
    name: Build-n-Run on ${{matrix.os}} with ${{matrix.compiler}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [dart]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Install mandatory packages for building
        run: ./apt_install_dart.sh && dart pub get
      - name: Create executable with ${{matrix.compiler}}
        run: dart compile exe -o dmtr bin/dmtr.dart
      - name: Run on ${{matrix.os}}
        run: ping -c1 google.com && ./dmtr -r google.com || ./dmtr -r 127.0.0.1

