name: build_and_run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_deb_and_run_once:
    name: Build, pack it in .deb, install, and run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Install mandatory packages for building
        run: |
          sudo apt install -y dpkg-dev devscripts debhelper
          misc/apt_install_dart.sh && dart pub get
      - name: Create .deb package
        run: |
          misc/build_deb.sh
          sudo dpkg -i debs/dmtr_*_*.deb
      - name: Test run
        run: ping -c1 google.com && dmtr -r google.com || dmtr -r 127.0.0.1
  build_snap:
    name: Build app and pack it in .snap
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - uses: snapcore/action-build@v1
        id: build-snap
      - name: Make sure it's built
        run: ls -l ${{ steps.build-snap.outputs.snap }}

